.PHONY: clean All

All:
	@echo "----------Building project:[ fdws - Release ]----------"
	@cd "fdws" && "$(MAKE)" -f  "fdws.mk"
clean:
	@echo "----------Cleaning project:[ fdws - Release ]----------"
	@cd "fdws" && "$(MAKE)" -f  "fdws.mk" clean
